DROP TABLE IF EXISTS task;

CREATE TABLE task (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT = UNIQUE NOT NULL,
    completed INTEGER, UNIQUE NOT NULL DEFAULT 0,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);